---
abstract: 'Add post_multipart to HTTP::Tiny'
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.010, CPAN::Meta::Converter version 2.150005'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: HTTP-Tiny-Multipart
provides:
  HTTP::Tiny::Multipart:
    file: lib/HTTP/Tiny/Multipart.pm
    version: '0.08'
requires:
  Carp: '0'
  File::Basename: '0'
  HTTP::Tiny: '0'
  MIME::Base64: '0'
resources:
  bugtracker: http://github.com/reneeb/HTTP-Tiny-Multipart/issues
  homepage: http://github.com/reneeb/HTTP-Tiny-Multipart
  repository: http://github.com/reneeb/HTTP-Tiny-Multipart.git
version: '0.08'
x_contributors:
  - 'Aran Deltac <bluefeet@gmail.com>'
  - 'Mark Glines <mark@glines.org>'
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
  - 'Renee Baecker <github@renee-baecker.de>'
  - 'reneeb <info@perl-services.de>'
  - 'Renee <reb@perl-services.de>'
  - 'Stephen Thirlwall <sdt@dr.com>'
x_serialization_backend: 'YAML::Tiny version 1.69'
